# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authenticator.proto for package 'study20180216'
# Original file comments:
# *
# 認証。

require 'grpc'
require 'authenticator_pb'

module Study20180216
  module Authenticator
    # *
    # ページの CRUD を行うサービス。
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'study20180216.Authenticator'

      # / 登録する。
      rpc :Register, RegisterRequest, RegisterResponse
      # / 認証する。
      rpc :Authenticate, AuthRequest, AuthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
