# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticator.proto

require 'google/protobuf'

require 'common_pb'
require 'credentials_pb'
require 'user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "study20180216.RegisterRequest" do
    optional :user, :message, 1, "study20180216.User"
    optional :password, :message, 2, "study20180216.Password"
  end
  add_message "study20180216.RegisterResponse" do
    optional :status, :enum, 1, "study20180216.RegisterResponse.Status"
    oneof :result do
      optional :user, :message, 2, "study20180216.User"
      optional :error, :message, 3, "study20180216.Error"
    end
  end
  add_enum "study20180216.RegisterResponse.Status" do
    value :OK, 0
    value :ERROR, 1
  end
  add_message "study20180216.AuthRequest" do
    optional :credentials, :message, 1, "study20180216.Credentials"
  end
  add_message "study20180216.AuthResponse" do
    optional :status, :enum, 1, "study20180216.AuthResponse.Status"
    oneof :result do
      optional :user, :message, 2, "study20180216.User"
      optional :error, :message, 3, "study20180216.Error"
    end
  end
  add_enum "study20180216.AuthResponse.Status" do
    value :OK, 0
    value :ERROR, 1
  end
end

module Study20180216
  RegisterRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.RegisterRequest").msgclass
  RegisterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.RegisterResponse").msgclass
  RegisterResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.RegisterResponse.Status").enummodule
  AuthRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.AuthRequest").msgclass
  AuthResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.AuthResponse").msgclass
  AuthResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.AuthResponse.Status").enummodule
end
