# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credentials.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "study20180216.AccessTokenCredentials" do
    optional :access_token, :message, 1, "study20180216.AccessToken"
  end
  add_message "study20180216.PasswordCredentials" do
    optional :password, :message, 1, "study20180216.Password"
  end
  add_message "study20180216.Credentials" do
    oneof :credentials do
      optional :access_token, :message, 1, "study20180216.AccessTokenCredentials"
      optional :password, :message, 2, "study20180216.PasswordCredentials"
    end
  end
  add_message "study20180216.Password" do
    optional :id, :string, 1
    oneof :password do
      optional :raw_password, :string, 2
      optional :hashed_password, :string, 3
    end
  end
  add_message "study20180216.AccessToken" do
    optional :token, :string, 2
  end
end

module Study20180216
  AccessTokenCredentials = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.AccessTokenCredentials").msgclass
  PasswordCredentials = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PasswordCredentials").msgclass
  Credentials = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.Credentials").msgclass
  Password = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.Password").msgclass
  AccessToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.AccessToken").msgclass
end
