# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: notebook.proto for package 'study20180216'
# Original file comments:
# *
# ノート。
#

require 'grpc'
require 'notebook_pb'

module Study20180216
  module Notebook
    # *
    # ページの CRUD を行うサービス。
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'study20180216.Notebook'

      # / ページを作成する。
      rpc :CreatePage, PageRequest, PageResponse
      # / ページを取得する。
      rpc :GetPage, PageRequest, PageResponse
      # / ページ一覧を取得する。
      rpc :ListPages, PagesRequest, PagesResponse
      # / ページを更新する。
      rpc :UpdatePage, PageRequest, PageResponse
      # / ページを削除する。
      rpc :DeletePage, PageRequest, PageResponse
    end

    Stub = Service.rpc_stub_class
  end
end
