# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notebook.proto

require 'google/protobuf'

require 'common_pb'
require 'credentials_pb'
require 'user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "study20180216.Page" do
    optional :id, :string, 1
    optional :title, :string, 2
    optional :content, :string, 3
    optional :editor, :message, 4, "study20180216.User"
  end
  add_message "study20180216.Pages" do
    repeated :members, :message, 1, "study20180216.Page"
  end
  add_message "study20180216.PageRequest" do
    optional :credentials, :message, 1, "study20180216.Credentials"
    optional :page, :message, 2, "study20180216.Page"
  end
  add_message "study20180216.PageResponse" do
    optional :status, :enum, 1, "study20180216.PageResponse.Status"
    oneof :result do
      optional :page, :message, 2, "study20180216.Page"
      optional :error, :message, 3, "study20180216.Error"
    end
  end
  add_enum "study20180216.PageResponse.Status" do
    value :OK, 0
    value :ERROR, 1
  end
  add_message "study20180216.PagesRequest" do
    optional :credentials, :message, 1, "study20180216.Credentials"
    optional :page_number, :uint32, 2
    optional :query, :string, 3
  end
  add_message "study20180216.PagesResponse" do
    optional :status, :enum, 1, "study20180216.PagesResponse.Status"
    oneof :result do
      optional :pages, :message, 2, "study20180216.Pages"
      optional :error, :message, 3, "study20180216.Error"
    end
  end
  add_enum "study20180216.PagesResponse.Status" do
    value :OK, 0
    value :ERROR, 1
  end
end

module Study20180216
  Page = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.Page").msgclass
  Pages = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.Pages").msgclass
  PageRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PageRequest").msgclass
  PageResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PageResponse").msgclass
  PageResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PageResponse.Status").enummodule
  PagesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PagesRequest").msgclass
  PagesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PagesResponse").msgclass
  PagesResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.PagesResponse.Status").enummodule
end
