# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "study20180216.User" do
    optional :id, :string, 1
    optional :name, :string, 2
    repeated :roles, :enum, 3, "study20180216.User.Role"
  end
  add_enum "study20180216.User.Role" do
    value :EDITOR, 0
  end
end

module Study20180216
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.User").msgclass
  User::Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("study20180216.User.Role").enummodule
end
